# Generated by Django 6.0.6 on 2026-08-10 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tailored', 'Tailored'), ('applied', 'Applied'), ('interview', 'Interviewing'), ('rejected', 'Rejected'), ('offer', 'Offer Received')], default='draft', max_length=50)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='knowledge_base.jobposting')),
                ('resume_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resume.resumeversion')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='knowledge_base.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
