version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
