# Generated by Django 6.0.6 on 2026-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_userprofile_full_name_userprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='total_cost',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
    ]
