# Generated by Django 6.0.6 on 2026-07-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_agentrun_completion_tokens_agentrun_prompt_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('parent_checkpoint_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkpoint_data', models.BinaryField()),
                ('metadata_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('thread_id', 'checkpoint_id')},
            },
        ),
        migrations.CreateModel(
            name='AgentCheckpointWrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_id', models.CharField(max_length=255)),
                ('task_id', models.CharField(max_length=255)),
                ('idx', models.IntegerField()),
                ('channel', models.CharField(max_length=255)),
                ('value', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('thread_id', 'checkpoint_id', 'task_id', 'idx')},
            },
        ),
    ]
