# Generated by Django 6.0.6 on 2026-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_agentmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='selected_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='selected_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
