# Generated by Django 6.0.6 on 2026-07-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_conversation_selected_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
