# Generated by Django 6.0.6 on 2026-07-21 03:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_message_completion_tokens_message_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('bullet_points', models.JSONField(default=list)),
                ('tech_stack', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='memory.userprofile')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_text', models.TextField()),
                ('parsed_summary', models.TextField(blank=True, null=True)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('responsibilities', models.JSONField(default=list)),
                ('ats_keywords', models.JSONField(default=list)),
                ('experience_years_required', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='memory.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalKnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Senior Software Engineer', max_length=255)),
                ('headline', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('target_roles', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='memory.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('architecture_notes', models.TextField(blank=True, null=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('impact_metrics', models.JSONField(default=list)),
                ('project_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='memory.userprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=255)),
                ('template_name', models.CharField(default='modern', max_length=100)),
                ('structured_spec', models.JSONField(default=dict)),
                ('latex_code', models.TextField()),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('generation_latency_ms', models.IntegerField(default=0)),
                ('llm_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='memory.jobposting')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='memory.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0)),
                ('present_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('weak_skills', models.JSONField(default=list)),
                ('formatting_score', models.IntegerField(default=100)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_report', to='memory.resumeversion')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tailored', 'Tailored'), ('applied', 'Applied'), ('interview', 'Interviewing'), ('rejected', 'Rejected'), ('offer', 'Offer Received')], default='draft', max_length=50)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memory.userprofile')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='memory.jobposting')),
                ('resume_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='memory.resumeversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('frameworks', 'Frameworks & Libraries'), ('databases', 'Databases & Storage'), ('cloud_devops', 'Cloud & DevOps'), ('ai_ml', 'AI & Machine Learning'), ('tools', 'Tools & Platforms'), ('concepts', 'Concepts & Architecture')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(default='Expert', max_length=50)),
                ('years_experience', models.IntegerField(default=1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='memory.userprofile')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('user_profile', 'name')},
            },
        ),
    ]
