# Generated by Django 6.0.6 on 2026-07-31 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0008_experience_jobposting_professionalknowledgebase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latex_source', models.TextField()),
                ('preview_image', models.CharField(blank=True, max_length=500, null=True)),
                ('supported_sections', models.JSONField(default=list)),
                ('variables', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='resume_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='memory.resumetemplate'),
        ),
    ]
