# Generated by Django 6.0.6 on 2026-07-31 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0009_resumetemplate_resumeversion_resume_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('ats_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExperienceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='memory.experience')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_links', to='memory.project')),
            ],
            options={
                'unique_together': {('project', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='SkillExperienceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='memory.experience')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_links', to='memory.skill')),
            ],
            options={
                'unique_together': {('skill', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='SkillProjectLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_links', to='memory.project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='memory.skill')),
            ],
            options={
                'unique_together': {('skill', 'project')},
            },
        ),
    ]
