"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
def load_env_file():
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, val = line.split('=', 1)
                    key = key.strip()
                    val = val.strip().strip("'").strip('"')
                    os.environ.setdefault(key, val)

load_env_file()

# Allow database operations in threads with running event loops
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qs+p#ex#4di*v=m6uqjim74r4a3r5ar&o*2^nk!n#8+1sivr3a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed Hostnames
ALLOWED_HOSTS=[]
allowed_hosts_env = os.environ.get("ALLOWED_HOSTS", "")
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', '127.0.0.1:8000', 'localhost:8000', 'shareholders-workplace-like-morgan.trycloudflare.com']

# CSRF Trusted Origins
csrf_origins_env = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(",") if origin.strip()]

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'django_celery_beat',
    'channels',
    'llm',
    'knowledge_base',
    'prospecting',
    'integrations.instagram',
    'integrations.linkedin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ── Django Unfold Admin UI Configuration ──────────────────────────────────────
UNFOLD = {
    "SITE_TITLE": "Nomad Bot",
    "SITE_HEADER": "Nomad Bot Admin",
    "SITE_SUBHEADER": "B2B Prospecting Engine",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": None,
    "SITE_SYMBOL": "radar",          # Material symbol used as favicon fallback
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "THEME": "dark",                 # 'dark' | 'light' | None (respects OS)
    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "75 85 99",
            "default-dark": "209 213 219",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50": "240 245 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Prospecting",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Intake Requests",
                        "icon": "inbox",
                        "link": "/admin/prospecting/prospectingrequest/",
                    },
                    {
                        "title": "Spec Versions",
                        "icon": "description",
                        "link": "/admin/prospecting/prospectingspecificationversion/",
                    },
                    {
                        "title": "Campaigns",
                        "icon": "campaign",
                        "link": "/admin/prospecting/prospectingcampaign/",
                    },
                    {
                        "title": "Discovery Runs",
                        "icon": "search",
                        "link": "/admin/prospecting/discoveryrun/",
                    },
                    {
                        "title": "Discoveries",
                        "icon": "explore",
                        "link": "/admin/prospecting/discovery/",
                    },
                    {
                        "title": "Discovery Leads",
                        "icon": "link",
                        "link": "/admin/prospecting/discoverylead/",
                    },
                ],
            },
            {
                "title": "Leads",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Companies",
                        "icon": "business",
                        "link": "/admin/prospecting/leadcompany/",
                    },
                    {
                        "title": "Contacts",
                        "icon": "contacts",
                        "link": "/admin/prospecting/leadcontact/",
                    },
                    {
                        "title": "Qualifications",
                        "icon": "verified",
                        "link": "/admin/prospecting/qualification/",
                    },
                    {
                        "title": "Evidence",
                        "icon": "article",
                        "link": "/admin/prospecting/evidence/",
                    },
                    {
                        "title": "Company Signals",
                        "icon": "sensors",
                        "link": "/admin/prospecting/companysignal/",
                    },
                ],
            },
            {
                "title": "Outreach",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Target Lists",
                        "icon": "list",
                        "link": "/admin/prospecting/targetlist/",
                    },
                    {
                        "title": "Enrollments",
                        "icon": "how_to_reg",
                        "link": "/admin/prospecting/campaignenrollment/",
                    },
                    {
                        "title": "Email Sequences",
                        "icon": "mark_email_read",
                        "link": "/admin/prospecting/emailsequence/",
                    },
                    {
                        "title": "Email Messages",
                        "icon": "mail",
                        "link": "/admin/prospecting/emailmessage/",
                    },
                    {
                        "title": "Inbound Replies",
                        "icon": "reply",
                        "link": "/admin/prospecting/inboundreply/",
                    },
                ],
            },
            {
                "title": "LLM",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Prompt Runs",
                        "icon": "analytics",
                        "link": "/admin/llm/promptrun/",
                    },
                    {
                        "title": "Prompts",
                        "icon": "auto_awesome",
                        "link": "/admin/llm/llmprompt/",
                    },
                    {
                        "title": "Agent Configs",
                        "icon": "smart_toy",
                        "link": "/admin/llm/agentconfig/",
                    },
                ],
            },
            {
                "title": "Instagram CRM",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Accounts",
                        "icon": "account_circle",
                        "link": "/admin/instagram_integration/instagramaccount/",
                    },
                    {
                        "title": "Automations",
                        "icon": "bolt",
                        "link": "/admin/instagram_integration/instagramautomation/",
                    },
                    {
                        "title": "Webhook Events",
                        "icon": "webhook",
                        "link": "/admin/instagram_integration/instagramwebhookevent/",
                    },
                    {
                        "title": "Actions Log",
                        "icon": "history",
                        "link": "/admin/instagram_integration/instagramautomationaction/",
                    },
                    {
                        "title": "OAuth States",
                        "icon": "vpn_key",
                        "link": "/admin/instagram_integration/instagramoauthstate/",
                    },
                ],
            },
            {
                "title": "System",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "User Profiles",
                        "icon": "manage_accounts",
                        "link": "/admin/knowledge_base/userprofile/",
                    },
                ],
            },
        ],
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Redis Configuration (Supports REDIS_URL for remote/production or REDIS_HOST for local)
REDIS_URL = os.environ.get("REDIS_URL", "").strip().strip("'").strip('"')
if REDIS_URL.startswith("REDIS_URL="):
    REDIS_URL = REDIS_URL[len("REDIS_URL="):].strip().strip("'").strip('"')

redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")

if REDIS_URL:
    channel_layer_hosts = [REDIS_URL]
    celery_broker = REDIS_URL
    celery_backend = REDIS_URL
    cache_location = REDIS_URL
else:
    channel_layer_hosts = [(redis_host, 6379)]
    celery_broker = f'redis://{redis_host}:6379/0'
    celery_backend = f'redis://{redis_host}:6379/0'
    cache_location = f'redis://{redis_host}:6379/1'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": channel_layer_hosts,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import sys
import dj_database_url

if 'test' in sys.argv:
    from django.test import TestCase, TransactionTestCase
    TestCase.databases = {'default'}
    TransactionTestCase.databases = {'default'}
    
    from django.db.backends.signals import connection_created
    from django.dispatch import receiver
    
    @receiver(connection_created)
    def set_sqlite_wal(sender, connection, **kwargs):
        if connection.vendor == 'sqlite':
            with connection.cursor() as cursor:
                cursor.execute('PRAGMA journal_mode=WAL;')
                cursor.execute('PRAGMA synchronous=NORMAL;')
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30000,
            }
        },
    }
else:
    database_url = os.environ.get("DATABASE_URL", "").strip().strip("'").strip('"')
    if database_url.startswith("DATABASE_URL="):
        database_url = database_url[len("DATABASE_URL="):].strip().strip("'").strip('"')

    if database_url:
        default_db_config = dj_database_url.parse(
            database_url,
            conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", 0)),
            ssl_require=os.environ.get("DB_SSL_REQUIRE", "False").lower() in ("true", "1", "yes") or "supabase" in database_url,
        )
    else:
        default_db_config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'aios_db'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'password'),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.environ.get('POSTGRES_PORT', '5433'),
        }

    DATABASES = {
        'default': default_db_config,
    }

DATABASE_ROUTERS = []


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Per-run discovery observability. Each run gets a JSON trace plus a
# self-contained HTML viewer in this directory.
DISCOVERY_TRACE_ENABLED = os.environ.get("DISCOVERY_TRACE_ENABLED", "True").lower() in ("true", "1", "yes")
DISCOVERY_TRACE_DIR = Path(os.environ.get("DISCOVERY_TRACE_DIR", BASE_DIR / "discovery_traces"))
DISCOVERY_TRACE_STRING_LIMIT = int(os.environ.get("DISCOVERY_TRACE_STRING_LIMIT", "100000"))

# Celery Settings
CELERY_BROKER_URL = celery_broker
CELERY_RESULT_BACKEND = celery_backend
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = 'test' in sys.argv
CELERY_TASK_EAGER_PROPAGATES = CELERY_TASK_ALWAYS_EAGER
CELERY_BEAT_SCHEDULE = {
    'linkedin-fill-content-queues': {
        'task': 'linkedin.fill_content_queues',
        'schedule': 60 * 60,
    },
    'linkedin-publish-due-posts': {
        'task': 'linkedin.publish_due_posts',
        'schedule': 60,
    },
}


# Cache backend (Redis) for distributed task locking
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": cache_location,
    }
}

# Standard logger configuration to stream info logs to console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} [{name}]: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'prospecting': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'llm': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# REST Framework API Documentation
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Nomad API',
    'DESCRIPTION': 'Interactive API documentation for Nomad Prospecting and Tool Platform.',
    'VERSION': '3.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


# Cap leads collected per discovery run
PROSPECTING_MAX_LEADS_PER_RUN = int(os.environ.get("PROSPECTING_MAX_LEADS_PER_RUN", 10))

# ── Instagram Integration Settings ──────────────────────────────────────────
INSTAGRAM_APP_ID = os.environ.get("INSTAGRAM_APP_ID", "")
INSTAGRAM_APP_SECRET = os.environ.get("INSTAGRAM_APP_SECRET", "")
INSTAGRAM_REDIRECT_URI = os.environ.get(
    "INSTAGRAM_REDIRECT_URI",
    "http://localhost:8000/api/v3/integrations/instagram/oauth/callback/"
)
INSTAGRAM_WEBHOOK_VERIFY_TOKEN = os.environ.get("INSTAGRAM_WEBHOOK_VERIFY_TOKEN", "")
INSTAGRAM_GRAPH_API_VERSION = os.environ.get("INSTAGRAM_GRAPH_API_VERSION", "v21.0")
INSTAGRAM_TOKEN_ENCRYPTION_KEY = os.environ.get("INSTAGRAM_TOKEN_ENCRYPTION_KEY", "")
INSTAGRAM_HTTP_TIMEOUT_SECONDS = int(os.environ.get("INSTAGRAM_HTTP_TIMEOUT_SECONDS", "15"))
INSTAGRAM_MAX_RETRY_ATTEMPTS = int(os.environ.get("INSTAGRAM_MAX_RETRY_ATTEMPTS", "3"))

# ── LinkedIn Content Automation ─────────────────────────────────────────────
# Direct LinkedIn posting is intentionally not performed here. Configure an
# approved social scheduler (Buffer, Make, Zapier, n8n, etc.) as a webhook.
LINKEDIN_PUBLISH_WEBHOOK_URL = os.environ.get("LINKEDIN_PUBLISH_WEBHOOK_URL", "").strip()
LINKEDIN_PUBLISH_WEBHOOK_SECRET = os.environ.get("LINKEDIN_PUBLISH_WEBHOOK_SECRET", "").strip()
LINKEDIN_HTTP_TIMEOUT_SECONDS = int(os.environ.get("LINKEDIN_HTTP_TIMEOUT_SECONDS", "60"))
LINKEDIN_GENERATE_IMAGES = os.environ.get("LINKEDIN_GENERATE_IMAGES", "False").lower() in ("true", "1", "yes")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_IMAGE_MODEL = os.environ.get("OPENAI_IMAGE_MODEL", "gpt-image-1.5").strip()
PUBLIC_BACKEND_URL = os.environ.get("PUBLIC_BACKEND_URL", "http://localhost:8000").strip().rstrip("/")

# ── Remote Celery Worker Keep-Alive & Wake Configuration ─────────────────────
WORKER_1_URL = os.environ.get("WORKER_1_URL", "http://127.0.0.1:10000").rstrip("/")
WORKER_2_URL = os.environ.get("WORKER_2_URL", "http://127.0.0.1:10001").rstrip("/")
WORKER_WAKE_TOKEN = os.environ.get("WORKER_WAKE_TOKEN", "").strip()
WORKER_NAME = os.environ.get("WORKER_NAME", "").strip()



