# Generated by Django 6.0.6 on 2026-08-10 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latex_source', models.TextField()),
                ('preview_image', models.CharField(blank=True, max_length=500, null=True)),
                ('supported_sections', models.JSONField(default=list)),
                ('variables', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=255)),
                ('template_name', models.CharField(default='modern', max_length=100)),
                ('structured_spec', models.JSONField(default=dict)),
                ('latex_code', models.TextField()),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('generation_latency_ms', models.IntegerField(default=0)),
                ('llm_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='knowledge_base.jobposting')),
                ('resume_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume.resumetemplate')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='knowledge_base.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ATSReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0)),
                ('present_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('weak_skills', models.JSONField(default=list)),
                ('formatting_score', models.IntegerField(default=100)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_report', to='resume.resumeversion')),
            ],
        ),
    ]
